package com.example.accessingdatamysql;

public enum Nakshtra {
    UNSPECIFIED,ASHWINI,ARDRA,ASLESHA,ANURADHA,BHARANI,
    CHITRA,DHANISHTA,HASTA,JYESHTA,KRITTIKA,MOOLA,MAGHA,
    MRIGASIRA,PUSHYA,PURVA_PHALGINI,PURVA_BHADRA,PURVA_SHADHA,
    PUNARVASU,ROHINI,SWATI,REVATI,SHATTARKA,SHRAVAN,
    UTTARA_PHALGUNI,UTTARA_BHADRA,UTTARA_SHADHA,VISHAKHA
}
